### ISSUE TITLE
Let's Encrypt certificate of go-fed.org expired

### ISSUE THREAD

**Issue by RoestVrijStaal** [go-fed/site#5]
Multiple browsers reported me that the certificate expired at 09-06-2020

Please renew the certificate, or don't use HTTPS at all. 

After overriding my browser's warning, I figured out applying the latter choice doesn't seem to hurt much, since the visitors don't submit filled forms or send "interesting data" in any other way to the server.

**Comment by cjslep** [comment]
Thanks for the reminder -- I will renew the cert ASAP.

I strongly prefer keeping HTTPS -- even though there's no forms on the website, I still do not want content MITM'd.

**Comment by cjslep** [comment]
It should be renewed now -- thanks a ton for bringing this to my attention!

**Comment by RoestVrijStaal** [comment]
You're welcome :+1:
